//! Extras: the `[<section>]` modules built on top of the core.
//!
//! Upstream keeps these in `klippy/extras/`; here they are a submodule of
//! `core::klippy` for the same reason: they are *users* of the core (the pin
//! layer, the G-Code dispatcher, the MCU configuration), not part of it. The
//! loader reaches them through its factory table (`load.rs`), so the core never
//! imports them.

pub mod ad5206;
pub mod adc_scaled;
pub mod adc_temperature;
pub mod adxl345;
pub mod bed_mesh;
pub mod bed_screws;
pub mod bed_tilt;
pub mod bltouch;
pub mod board_pins;
pub mod bulk_sensor;
pub(crate) mod bus_debug;
pub mod buttons;
pub mod carriage;
pub mod controller_fan;
pub mod delta_calibrate;
pub mod display;
pub mod display_status;
pub mod ds18b20;
pub mod endstop_phase;
pub mod error_mcu;
pub mod exclude_object;
pub mod extruder;
pub mod extruder_stepper;
pub mod fan;
pub mod fan_generic;
pub mod filament_motion_sensor;
pub mod filament_switch_sensor;
pub mod force_move;
pub mod gcode_arcs;
pub mod gcode_macro;
pub mod gcode_move;
pub mod heater_bed;
pub mod heater_fan;
pub mod heater_generic;
pub mod heaters;
pub mod homing_override;
pub mod hx71x;
pub mod i2c_device;
pub mod idex_modes;
pub mod input_shaper;
pub mod ldc1612;
pub mod led;
pub mod load_cell;
pub mod manual_probe;
pub mod manual_stepper;
pub mod mpu9250;
pub mod output_pin;
pub mod pause_resume;
pub mod probe;
pub mod probe_eddy_current;
pub mod pulse_counter;
pub mod pwm_cycle_time;
pub mod pwm_tool;
pub mod quad_gantry_level;
pub mod query_endstops;
pub mod resonance_tester;
pub mod safe_z_home;
pub mod screws_tilt_adjust;
pub mod sdcard_loop;
pub mod servo;
pub mod shaper_defs;
pub mod smart_effector;
pub mod spi_device;
pub mod spi_temperature;
pub mod static_digital_output;
pub mod stepper;
pub mod stepper_enable;
pub mod temperature_combined;
pub mod temperature_fan;
pub mod temperature_mcu;
pub mod temperature_sensor;
pub mod template;
pub mod tmc;
pub mod tmc2208;
pub mod tmc2209;
pub mod tmc_uart;
pub mod toolhead;
pub mod trigger_analog;
pub mod verify_heater;
pub mod virtual_sdcard;
pub mod z_tilt;
